### PR TITLE
Try to steal formatting config upon every flush

### PR DESCRIPTION
**Pull request by keynslug**
So that logging output in tests would reflect most recent logger configuration updates. Which would make possible to setup logger in `init_per_suite/1` for example.

### CODE REVIEW

**Comment by ferd** [comment]
This actually changes only the formatting done by log_to_binary/2, but does not change anything related to the log handler which is only set once at the program start. You would also need to diff the config and apply updates every time it changes if you wanted to do that.

I'm suspecting this PR is not doing exactly what you intend according to the current description.

**Comment by keynslug** [comment]
Yeah, I had an impression that I was missing something, just was not sure what exactly.

> This actually changes only the formatting done by log_to_binary/2...

Right, I should have probably make it clear that log message formatting in the context of new OTP-21 logger is my primary concern here.

> ...but does not change anything related to the log handler which is only set once at the program start.

This behaviour's still quite confusing to me. I thought that log handler's only purpose is to [relay log messages to the event handler](https://github.com/ferd/cth_readable/blob/c1a7dac38d39bc4174fb3a6caae85414221acccb/src/cth_readable_failonly.erl#L294), thus it doesn't really matter what configuration is set at the program start because the log handler doesn't really format anything. Even less so considering that the handler concerns itself with [formatter configuration only](https://github.com/ferd/cth_readable/blob/c1a7dac38d39bc4174fb3a6caae85414221acccb/src/cth_readable_failonly.erl#L313). What am I missing here?

**Comment by ferd** [comment]
Ah yeah you're right. I didn't recall shedding the rest of it (like log levels and filters), but that makes sense there.

**Comment by keynslug** [comment]
Thanks!

**Comment by ferd** [comment]
Published to hex, see https://github.com/erlang/rebar3/pull/2165 for the integration PR.

**Pull request merged**
