### PR TITLE
Make docs a bit more easier to understand

### PR DESCRIPTION
**Pull request by jaseemabid**
It took _me_ a while to figure out which config file. Also, mention that a dependency needs to be specified.

### CODE REVIEW

**Comment by ferd** [comment]
Assuming you use `rebar3`, as shown in your snippet, means that you shouldn't put the big `{deps, ...}` tuple at the top-level. The current config shown has:

``` erlang
{profiles, [
    {test, [{deps, [cth_readable]}]}
]}.
```

Which in rebar3, means that it will go fetch the `cth_readable` package on hex.pm for test runs only and work fine. 

We would need to take out the `{deps, ...}` tuple for it to be right. If you'd rather add instructions for other tools, we should re-think things. In fact, it's now part of rebar3 by default.

So something could be a bit like:

### rebar3

Supported and enabled by default

### rebar 2.x

``` erlang
{deps, [
    {cth_readable, {git, "https://github.com/ferd/cth_readable.git", {tag, "v1.1.0"}}}
]}.

 {ct_opts, [{ct_hooks, [cth_readable_failonly, cth_readable_shell]}]}.
 {ct_compile_opts, [{parse_transform, cth_readable_transform}]}.
```

### usage with erlang.mk

???

### usage by hand
1. install in `ERL_LIBS`
2. `ct_run --ct_hooks cth_readable_failonly [] and cth_readable_transform []`...

### usage with lager

```
<whatever is below the install instructions>
```

---

But under its current form, this documentation modification is just not correct.

**Comment by jaseemabid** [comment]
Did cth_redable get merged to rebar3-beta4 by any chance? I see pretty output now. 
Ref: https://twitter.com/jlouis666/status/668778622652710912

**Comment by ferd** [comment]
Yes, that is what I mean by "In fact, it's now part of rebar3 by default."

We put it in the project automatically so people no longer need to include it by hand in their stuff. It also automatically runs the `ct:pal` conversion for you.

**Comment by jaseemabid** [comment]
I'm only familiar with rebar and I just upgraded to latest rebar3 build solving my particular issue. 
I could reword the PR to handle rebar2 and rebar3 separately. 

PS: Thanks for the built in support in rebar3. Makes it a whole lot  easier.

**Comment by ferd** [comment]
Yeah, at least rebar3 and rebar2 separately would make more sense.

**Comment by jaseemabid** [comment]
@ferd Force updated topic branch.

**Comment by ferd** [comment]
Thanks!

**Comment by jaseemabid** [comment]
:+1:

**Pull request merged**
