### PR TITLE
Add support for ExUnit asserts

### PR DESCRIPTION
**Pull request by n-epifanov**
I had the need to format ExUnit asserts, it could be done easier from Elixir. What do you think about moving from Rebar to Mix? It seems to be a more effective tool.
PS This is a preview, not finished PR.

### CODE REVIEW

**Comment by ferd** [comment]
We won't move from rebar3 to mix because this library is _part_ of rebar3 and requiring mix to build rebar3 is a bad idea.

**Comment by n-epifanov** [comment]
What would be a better approach to implement this then?

**Comment by ferd** [comment]
I don't know. Would probably need to think of it. Essentially, since this library is used in the rebar3 build tool, it can't rely on Elixir without also forcing all Erlang users using it to also depend on Elixir.

Either we need to think of a kind of plugin system for it, or it can't just be used with it.

**Comment by ferd** [comment]
Another option is to use the rebar3 facilities to build Elixir dependencies as part of Erlang projects to work well, but this needs to be configurable in such a way that Rebar3 never actually uses it.

**Comment by n-epifanov** [comment]
That's right, I missed the point that Erlang users would need Elixir as well.
Thanks, I'll look into this approach with rebar3. It could be made with a conditional compilation: just one #ifdef block would be enough.

**Comment by n-epifanov** [comment]
Wow, I missed that you're the author of the great "Learn You Some Erlang for great good!". It's my go-to book for studying Erlang. Great-explained and interesting read at the same time. Thanks!
PS Never seen any book with so many beards :D

**Pull request closed without merging**
